### ISSUE TITLE
Word limitations with the Group Edit command

### ISSUE THREAD

**Issue by Nyxborne** [TheCrunchy/AlliancesPlugin#4]
While doing the "!group edit" command, the command only recognizes the first word. For example, my group is the Concord-of-Sanctuary. I type in "!group edit name Concord of Sanctuary" and it only recognizes "Concord". If i want to change my description, it will still only recognize 1 word.
For example, I type in "!group edit description To protect and defend the freedom of those that would take it." The description only recognize "To".

Please support multiple word edit commands.

**Comment by TheCrunchy** [comment]
It is supported, put it inside "" 

your example would be !group edit description "To protect and defend the freedom of those that would take it."
